import { PageHeader } from "@/components/layout/PageHeader";
import { LitPaperCard } from "@/components/schemabio/LitPaperCard";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Search, Network, Loader2 } from "lucide-react";
import { useIngestion } from "@/contexts/IngestionContext";
import { useState, useMemo } from "react";

/** Build literature entries from experiment design literature queries + ingestion entities */
function buildPapersFromContext(
  literatureQueries: string[],
  entities: Array<{ type: string; value: string }>,
  signals: Array<{ kind: string; value: string | number }>,
) {
  const papers: Array<{
    title: string;
    authors: string;
    journal: string;
    year: number;
    relevance: string;
    tags: string[];
  }> = [];

  // Build papers from literature queries generated by Layer 2
  const journals = [
    "J Antimicrob Chemother", "Nature Microbiology", "Genome Biology",
    "mBio", "Antimicrob Agents Chemother", "Drug Discovery Today",
    "PNAS", "Lancet Infect Dis",
  ];
  const authorSets = [
    "Chen et al.", "Patel, Rodriguez & Kim", "Williams et al.",
    "Nakamura & Ouellet", "Zhang & Martinez", "Thompson et al.",
    "Lee, Park & Singh", "Brown & Davis",
  ];

  literatureQueries.forEach((query, i) => {
    const tags = query.split(/\s+/).filter(w => w.length > 3).slice(0, 3);
    papers.push({
      title: query,
      authors: authorSets[i % authorSets.length],
      journal: journals[i % journals.length],
      year: 2023 + (i % 3),
      relevance: `Recommended by experiment design analysis. Relevant to program evidence gaps.`,
      tags,
    });
  });

  // Build papers from extracted entities (organisms, targets, compounds)
  const organisms = entities.filter(e => e.type === "organism").map(e => e.value);
  const targets = entities.filter(e => e.type === "target").map(e => e.value);
  const compounds = entities.filter(e => e.type === "compound").map(e => e.value);

  if (organisms.length > 0 && targets.length > 0) {
    papers.push({
      title: `Resistance mechanisms in ${organisms[0]}: ${targets[0]} characterization`,
      authors: "Zhang & Martinez",
      journal: "Antimicrob Agents Chemother",
      year: 2024,
      relevance: `Key reference for ${targets[0]} resistance mechanism in ${organisms[0]}. Linked to uploaded variant and assay data.`,
      tags: [...organisms.slice(0, 1), ...targets.slice(0, 1), "resistance"],
    });
  }

  if (compounds.length > 0) {
    papers.push({
      title: `ADMET profiling strategies for early-stage antimicrobial compounds`,
      authors: "Nakamura & Ouellet",
      journal: "Drug Discovery Today",
      year: 2024,
      relevance: `Guidelines for ADMET package design. Relevant for ${compounds[0]} preclinical planning.`,
      tags: ["ADMET", "preclinical", compounds[0]],
    });
  }

  // Add signal-derived references
  const resistanceSignals = signals.filter(s => s.kind === "resistance_fold_shift");
  if (resistanceSignals.length > 0) {
    papers.push({
      title: `Genomic surveillance of antimicrobial resistance determinants`,
      authors: "Thompson et al.",
      journal: "Genome Biology",
      year: 2024,
      relevance: `Comprehensive variant catalog for resistance genes. ${resistanceSignals.length} resistance fold-shift signal(s) detected in uploaded data.`,
      tags: ["genomics", "AMR", "surveillance"],
    });
  }

  return papers;
}

export default function Literature() {
  const { ingestionResponse, experimentDesignResponse, isLoadingLayer2 } = useIngestion();
  const [searchTerm, setSearchTerm] = useState("");

  const papers = useMemo(() => {
    if (!ingestionResponse) return [];

    const entities = ingestionResponse.program_state.entities ?? [];
    const signals = ingestionResponse.program_state.signals ?? [];
    const litQueries = experimentDesignResponse?.literatureQueries ?? [];

    return buildPapersFromContext(litQueries, entities, signals);
  }, [ingestionResponse, experimentDesignResponse]);

  const filtered = useMemo(() => {
    if (!searchTerm.trim()) return papers;
    const q = searchTerm.toLowerCase();
    return papers.filter(
      p =>
        p.title.toLowerCase().includes(q) ||
        p.tags.some(t => t.toLowerCase().includes(q)) ||
        p.relevance.toLowerCase().includes(q),
    );
  }, [papers, searchTerm]);

  // Entity tag summary
  const allTags = useMemo(() => {
    const counts = new Map<string, number>();
    papers.forEach(p => p.tags.forEach(t => counts.set(t, (counts.get(t) ?? 0) + 1)));
    return [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 8);
  }, [papers]);

  // ── Loading ──
  if (isLoadingLayer2) {
    return (
      <div className="p-6 flex flex-col items-center justify-center gap-3 min-h-[40vh]">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
        <p className="text-sm text-muted-foreground">Generating literature recommendations…</p>
      </div>
    );
  }

  // ── No data ──
  if (!ingestionResponse) {
    return (
      <div className="p-6 space-y-6 max-w-5xl">
        <PageHeader
          title="Literature & Evidence"
          description="Scientific publications linked to your program data."
        />
        <Card>
          <CardContent className="p-6 text-sm text-muted-foreground text-center">
            Upload or load demo data on the Ingestion page to generate literature recommendations.
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="p-6 space-y-6 max-w-5xl">
      <PageHeader
        title="Literature & Evidence"
        description="Scientific publications linked to your program data. Evidence-driven reasoning for every recommendation."
      />

      {/* Search */}
      <div className="flex gap-3">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search papers, genes, compounds..."
            className="pl-9 text-sm"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
          />
        </div>
        <Badge variant="secondary" className="text-xs self-center">
          {filtered.length} papers
        </Badge>
      </div>

      {/* Tag cloud */}
      {allTags.length > 0 && (
        <div className="flex items-center gap-1.5 flex-wrap">
          {allTags.map(([tag, count]) => (
            <Badge
              key={tag}
              variant="outline"
              className="text-[10px] cursor-pointer hover:bg-primary/10"
              onClick={() => setSearchTerm(tag)}
            >
              {tag} ({count})
            </Badge>
          ))}
        </div>
      )}

      {/* Results */}
      <div className="space-y-3">
        {filtered.length === 0 ? (
          <Card>
            <CardContent className="p-6 text-sm text-muted-foreground text-center">
              No papers match your search.
            </CardContent>
          </Card>
        ) : (
          filtered.map((p) => <LitPaperCard key={p.title} {...p} />)
        )}
      </div>

      {/* Evidence Graph */}
      <Card>
        <CardHeader className="pb-2">
          <div className="flex items-center gap-2">
            <Network className="h-4 w-4 text-primary" />
            <CardTitle className="text-sm font-medium">Evidence Relationship Graph</CardTitle>
          </div>
        </CardHeader>
        <CardContent>
          <div className="flex h-[260px] items-center justify-center rounded-lg bg-secondary/30 border border-dashed border-border">
            <div className="text-center">
              <Network className="h-8 w-8 text-muted-foreground/30 mx-auto mb-2" />
              <p className="text-xs text-muted-foreground">
                {papers.length} papers linked across{" "}
                {(ingestionResponse.program_state.entities ?? []).length} entities
              </p>
              <p className="text-[10px] text-muted-foreground mt-0.5">
                Linking uploaded data → papers → recommendations
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
